### ISSUE TITLE
crash after updating SimpleOres and SimpleCoreLib

### ISSUE THREAD

**Issue by Atlntssplayer** [Sinhika/simpletungsten#3]
Hello!
I had these two mods on an existing world in MC v. 1.16.4:

SimpleCoreLib-1.16.4-2.0.3.2.jar
SimpleOres2-1.16.4-2.4.3.0.jar

I updated them to:

SimpleCoreLib-1.16.4-2.0.4.3.jar
SimpleOres2-1.16.4-2.4.3.8.jar

After this update when I try to load my save, the game crashes after seconds, way before loading the world.

According to the log it has to do with this mod but I'm not a developer.

Please take a look at this issue, thank you!

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2020.12.21. 7:43
Description: mouseClicked event handler

java.lang.NoSuchMethodError: mod.alexndr.simplecorelib.world.OreGenUtils.buildOverworldOreFeature(Lnet/minecraft/block/BlockState;Lmod/alexndr/simplecorelib/config/ModOreConfig;)Lnet/minecraft/world/gen/feature/ConfiguredFeature;
	at mod.akkamaddi.simpletungsten.generation.OreGeneration.initOverworldFeatures(OreGeneration.java:41) ~[simpletungsten:1.16.4-2.3.1.0] {re:classloading}
	at mod.akkamaddi.simpletungsten.generation.OreGeneration.checkAndInitBiome(OreGeneration.java:26) ~[simpletungsten:1.16.4-2.3.1.0] {re:classloading}
	at mod.akkamaddi.simpletungsten.ForgeEventSubscriber.onBiomeLoading(ForgeEventSubscriber.java:27) ~[simpletungsten:1.16.4-2.3.1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_312_ForgeEventSubscriber_onBiomeLoading_BiomeLoadingEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.enhanceBiome(ForgeHooks.java:902) ~[forge:?] {re:classloading}
	at net.minecraft.world.biome.Biome.lambda$null$8(Biome.java:75) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:mixin,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Function8.lambda$null$6(Function8.java:22) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.util.Function4.lambda$null$2(Function4.java:14) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.serialization.DataResult$Instance.ap2(DataResult.java:315) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.datafixers.kinds.Applicative.ap4(Applicative.java:84) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$7.decode(RecordCodecBuilder.java:404) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport$IResourceAccess$RegistryAccess.func_241879_a(WorldSettingsImport.java:236) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport.func_241805_a_(WorldSettingsImport.java:131) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport.lambda$decode$5(WorldSettingsImport.java:105) ~[?:?] {re:classloading}
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport.func_241797_a_(WorldSettingsImport.java:104) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.DynamicRegistries.func_243610_a(DynamicRegistries.java:144) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.registry.DynamicRegistries.func_243608_a(DynamicRegistries.java:132) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.registry.WorldSettingsImport.func_244336_a(WorldSettingsImport.java:53) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.DynamicRegistries.func_239770_b_(DynamicRegistries.java:85) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.func_238191_a_(Minecraft.java:1681) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214443_e(SourceFile:407) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214438_a(SourceFile:317) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraft.client.gui.screen.WorldSelectionScreen.func_214325_f(SourceFile:53) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:computing_frames,re:classloading,re:mixin}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.10.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mod.akkamaddi.simpletungsten.generation.OreGeneration.initOverworldFeatures(OreGeneration.java:41) ~[simpletungsten:1.16.4-2.3.1.0] {re:classloading}
	at mod.akkamaddi.simpletungsten.generation.OreGeneration.checkAndInitBiome(OreGeneration.java:26) ~[simpletungsten:1.16.4-2.3.1.0] {re:classloading}
	at mod.akkamaddi.simpletungsten.ForgeEventSubscriber.onBiomeLoading(ForgeEventSubscriber.java:27) ~[simpletungsten:1.16.4-2.3.1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_312_ForgeEventSubscriber_onBiomeLoading_BiomeLoadingEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.enhanceBiome(ForgeHooks.java:902) ~[forge:?] {re:classloading}
	at net.minecraft.world.biome.Biome.lambda$null$8(Biome.java:75) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:mixin,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Function8.lambda$null$6(Function8.java:22) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.util.Function4.lambda$null$2(Function4.java:14) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.serialization.DataResult$Instance.ap2(DataResult.java:315) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.datafixers.kinds.Applicative.ap4(Applicative.java:84) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$7.decode(RecordCodecBuilder.java:404) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport$IResourceAccess$RegistryAccess.func_241879_a(WorldSettingsImport.java:236) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport.func_241805_a_(WorldSettingsImport.java:131) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport.lambda$decode$5(WorldSettingsImport.java:105) ~[?:?] {re:classloading}
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.util.registry.WorldSettingsImport.func_241797_a_(WorldSettingsImport.java:104) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.DynamicRegistries.func_243610_a(DynamicRegistries.java:144) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.registry.DynamicRegistries.func_243608_a(DynamicRegistries.java:132) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.registry.WorldSettingsImport.func_244336_a(WorldSettingsImport.java:53) ~[?:?] {re:classloading}
	at net.minecraft.util.registry.DynamicRegistries.func_239770_b_(DynamicRegistries.java:85) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.func_238191_a_(Minecraft.java:1681) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214443_e(SourceFile:407) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214438_a(SourceFile:317) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraft.client.gui.screen.WorldSelectionScreen.func_214325_f(SourceFile:53) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:computing_frames,re:classloading,re:mixin}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.screen.WorldSelectionScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.10.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}

**Comment by Sinhika** [comment]
Don't use the new SimpleOres & SimpleCoreLib with older SimpleOres add-ons, they are not compatible; back out the Simple Ores & SimpleCoreLib update and wait until the other SimpleOres mods are updated, too.. Anything uploaded prior to 2020-Dec-20 will have problems. I will be updating them as time allows, as they all have the same issue with configured features that I fixed in SimpleOres.

**Comment by Sinhika** [comment]
A new version of SimpleTungsten, compatible with the latest SimpleCoreLib, has been released: 1.16.4-2.3.2.1. It also fixes features registration issues.
